### ISSUE TITLE
Preset from a local file

### ISSUE THREAD

**Issue by kachkaev** [wooorm/unified-engine#17]
I've created an NPM module that is supposed to work as a remark preset inside other modules. Linting rules are defined in `index.js`. What I would like to do is to lint `README.md` in my preset module with the same rules as well.

I tried the following in `package.json`, but it did not work:

```bash
  "remarkConfig": {
    "presets": ["./index.js"]
  },
```

The solution was to create `.remarkrc.js` next to `package.json` with the following content:

```js
module.exports = require('./index.js');
```

After I've don this, `remark-cli` has started picking up my rules.

Although my problem is solved in general, I'm wondering if it is possible to avoid this extra `.remarkrc.js` file by being able to refer to a local preset in `package.json`. Maybe it is allowed already, it's just me doing something wrong. Sharing my solution as someone else might face the same problem.

**Comment by wooorm** [comment]
Weird, that should work: https://github.com/wooorm/remark-lint/blob/772eaf324bc91973bc36e83d8f351f13e3722b7b/package.json#L68-L69

Any reason you can think of why it doesn’t work in this case?

**Comment by kachkaev** [comment]
Removing `.js` worked for me, thanks for the hint @wooorm!
```js
  "remarkConfig": {
    "presets": ["./index"]
  },
```

Should there be support for both `./file.js` and `./file` or shall we close this issue?

**Comment by wooorm** [comment]
Is `load-plugin` in your `node_modules/` at the latest version? It should work, so it’s a bug.

Can you check if `./file` and `./file.js` behave the same as `./index` and `./index.js`?

**Comment by kachkaev** [comment]
`node_modules/load-plugin/package.json` shows version 2.0.0 (I remember doing a clean `npm install` before reporting the issue).

I've no idea why, but everything has started working now both for `./index` and `./index.js`. _[an emoji with mixed emotions]_ Sorry for a possible false alarm! I'll let know in this thread if something goes wrong again or if I realise what has happened in the first place.

**Comment by wooorm** [comment]
Great to hear, please do! 👍
