### ISSUE TITLE
Allowing `node_modules`

### ISSUE THREAD

**Issue by kgryte** [wooorm/unified-engine#2]
The blanket ban on _any_ path containing `node_modules` is problematic; see [finder.js](https://github.com/wooorm/unified-engine/blob/db7257f6320fe90344f59beb447e66b3f5c7c1ef/lib/finder.js#L40). Specifying whether files/paths should be ignored should be left to the `.remarkignore` file.

For instance, suppose I wanted to ignore only the top-level `node_modules` directory. My `.remarkignore` file (just as with a `.gitignore` file) would be

```
/node_modules/
```

If I wanted to ignore all paths containing `node_modules`, I could do

```
node_modules/
**/node_modules
```

But this is not how the `unified-engine` currently works. Instead, it just assumes that any path which has `node_modules` is off limits. This is problematic for project structures like

```
bin/
lib/node_modules/
lib/node_modules/**/node_modules/
node_modules/
test
```

where the top-level `node_modules` directory is reserved for external libraries and `lib` node modules directories are used for local modules. These local node modules are not in any sense "external" and will, for most cases, be considered part of the core library; e.g., tested and used like any other internal file.

Hence, I would suggest removing the blanket ban on `node_modules` and leave it to the user to specify if, and how, `node_modules` should be ignored.

**Comment by kgryte** [comment]
If you believe `node_modules` is the primary path to ignore and want to alleviate a user from having to always specify that any `node_modules` path be ignored, then this could be a default. However, that default should be superseded by any user defined configuration.

**Comment by wooorm** [comment]
Previously, it was the case that `node_modules` was a normal ignore pattern. I changed that in https://github.com/wooorm/unified-engine/commit/74eb209c1e4f8328cf98769cca709c60517caa2c.

I did that because the engine allows negation patterns to include previously ignored patterns. This can significantly decrease performance because *if* negations are used, all ignored paths must also be searched as nested files can be first ignored and later allowed by other patterns.

For example, the following ignore file:

```ini
!**/*.foo
```

Would otherwise result, on big `node_modules` directories, very poor performance. Note: This poor performance can also be found in JSCS and ESLint. I’m very happy that remark doesn’t have that problem.

In essence: I’d rather have great performance over allowing some `node_modules` to be searched. Sure, it’s a valid use case, but it’s not used very widely, right? On the other hand, if performance can be kept okay, I’m all for allowing this.

**Comment by kgryte** [comment]
@wooorm If `node_modules` cannot be searched, we basically cannot use `remark`, as we use local `node_modules` extensively. That this may not be a common pattern has less to do with its legitimacy and more to do with many developers' failure to understand the `require` algorithm and how to leverage it within applications.

I can understand performance concerns and your wanting to prevent users from doing the "wrong" thing, but, at the least, would be good to have the ability to 'opt-in'.

**Comment by wooorm** [comment]
@kgryte Yeah I agree about your use case, and I’d love to make it do-able but I’m as of yet unsure how to.

I did add a note about negation patterns though: [`ff1ab4d`](https://github.com/wooorm/unified-engine/commit/ff1ab4d27464266c8780507610e462d640df689d#diff-37a3563d62210766bb4a9f730ba13031R53), so may that’s enough?

**Comment by kgryte** [comment]
@wooorm could possibly use an example and maybe one highlighting this particular use case. Namely, if you ignore `node_modules/` and then use negation, you force `unified` to search `node_modules` for anything matching the negated pattern. For large `node_modules` dependency trees, this results is significant performance degradation.

Granted, this approach is buyer-beware and people will do ill-advised things and one response might be to say RTFM, but, then again, as a user, if you find yourself trying to use negation patterns, you may want to stop and consider the complexity implications regardless.

**Comment by kgryte** [comment]
Awesome! Thanks!

**Comment by wooorm** [comment]
You’ll still have to deal with the perf though, I believe :/

**Comment by kgryte** [comment]
@wooorm I typically don't use negated patterns, but I do provide a list of files I wanted, e.g., linted, For example,

``` bash
$ remark ./lib/node_modules/foo.md ./lib/node_modules/bar.md --use remark-lint
```

My understanding is that these will not, by default, be filtered against, correct?

**Comment by wooorm** [comment]
Unfortunately not, as `node_modules` are initially hidden, passing files in [triggers a failure](https://github.com/wooorm/unified-engine/blob/ad441661fb5b56014e1f857c48affb3ccf50b03e/lib/finder.js#L134-L138).

So you’ll still need an ignore file with a negated pattern.

P.S. ESLint does the same:

```txt
🚀  foo master: touch .index.js
🚀  foo master [?]: eslint .index.js 

~/foo/.index.js
  0:0  warning  File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override

✖ 1 problem (0 errors, 1 warning)
```

**Comment by kgryte** [comment]
Then the notion of "passing them in as 'globs'" is a bit confusing. And I would expect that, if I give exact filepaths, those should not be ignored.

**Comment by wooorm** [comment]
Could you expand on `notion of "passing them in as 'globs'" is a bit confusing`? I’m not quite getting it.

I quite like this behaviour. It’s most often the desired behaviour. And if it’s not, you can get around it. Preventing ignored files from being processed is also useful and prevents detrimental cases.

**Comment by kgryte** [comment]
@wooorm Revisiting this issue. Yes, I can see a possible use case for ignoring provided files; although, I am not sure this should be the responsibility of `remark`. If I am given a list of Markdown files to lint by some upstream utility and only want some of those files to be lint, I could filter them myself before passing them to `remark`.

Currently, with how ignore works with `remark`, if I explicitly generate a list of files to lint, for example, I have to try and configure `remark` to not override my file list and to not ignore files based on some internal rules. This is a frustrating experience. Even if I use negated patterns, `remark` still ignores my explicitly provided list.

Thus to circle back to "passing them in as 'globs'", I am referring to the fact that globs and exact file paths seem to be treated differently. The case being that I have exact file paths (some of which include `node_modules` in the path), and, even if I include `!node_modules` or some other variant in the `remarkignore` file, these files are being ignored. The only way to get around this is by modifying [L193](https://github.com/wooorm/unified-engine/blob/master/lib/ignore.js#L193) in `ignore.js` to

``` javascript
return isHidden(basename);
```
With regard to "most often the desired behavior", I am not sure about this. Particularly in shell pipelines, a more common use case is where 1) a list of files is generated (e.g., using `find`) and 2) this list is piped to a downstream utility which then operates on those files (e.g., `grep`).

By supporting globbing, `remark` interjects itself into mandating particular ways of compiling file lists on which to operate. Particularly for my use cases, I am extensively compiling various lists of files (e.g., Markdown files), on which I want to independently operate (e.g., linting). However, because of how ignore works, I am not able to use `remark`.

What is desired is that, if I give an exact file list, `remark` has the option of acting in such a way as considering that list as authoritative, and thus not requiring any filtering.

**Comment by wooorm** [comment]
Sorry, I didn’t have time to review this at the time, and of course forgot about it... 😒 

Thanks for revisiting; I’m not entirely sure anymore how this works internally, and why it works this way.
I have plans for changing the workings of unified-engine a bit, and I hope that I can familiarise myself again with the code by doing that, and form an opinion on your problem!

**Comment by kgryte** [comment]
Cool. In the meantime, I will just use a modified (read: hacked) version of `remark` (and `unified-engine`) which will allow us to lint our Markdown files.

**Comment by kgryte** [comment]
__Update__: using "patched" versions of `unified-engine` --> `unified-args` --> `remark-cli` is not particularly viable, as `remark-cli` is part of a monorepo. Because `npm` does not allow installing from Git subdirectories (see npm/npm#2974), no elegant solution exists to install a version of `remark-cli`, which uses patched dependencies.

**Comment by kgryte** [comment]
@wooorm Another update. I am not able to lint Markdown files in the `.github` directory, even when using negated patterns. Once again, I am passing `remark-lint` a set of exact filenames I want to lint. `unified-engine` correctly recognizes the negated pattern (e.g., `!.github`), but `minimatch` does not return `true`. I tried several different pattern variants, but none allowed me to lint issue and pull request templates in the `.github` directory.

This is another case where overriding a user-supplied file list by filtering using some internally defined criteria causes undesired behavior. Namely, preventing the user from processing an explicitly defined list of files.

**Comment by wooorm** [comment]
Ah, that sucks. Sorry.

I’ve started work on rewriting the engine. I’ve just completed replacing the finder to work as expected.
What remains is:

a) the ignorer, which should work per-file instead of based on the CWD, and should return whether file paths are explicitly ignored (through ignore files) or implicitly (`.hidden` and `node_modules/hidden`);
b) presets should work based on functions instead of file-paths. This is something off-topic but I’d like to release it together so the rest of the ecosystem can update too.

Sorry it’s taking a while. I’m moving, starting start-ups, and it’s a rather big project to deal with.

Thanks for waiting! 🍻

**Comment by wooorm** [comment]
I’ve rewritten the find and ignore mechanism: https://github.com/wooorm/unified-engine/tree/new-find-and-ignore. Could you try the branch and see if it works, as expected, for you?

I haven’t updated the docs yet, but it should be more straightforward now.

**Comment by kgryte** [comment]
Will try and do so tomorrow.

**Comment by wooorm** [comment]
Perfect, thanks! 👍

**Comment by wooorm** [comment]
Ping :)

**Comment by wooorm** [comment]
@kgryte Ping!

**Comment by kgryte** [comment]
@wooorm Used the branch. Was able to get the same results as my patched (hacked) version. Hence, my current assessment is that the find and ignore mechanism works in accordance with my expectations.
